"""Experimental bounded-lookahead DE2 parser.

This module is deliberately separate from production ``lz.py``. It provides
an apples-to-apples parser experiment: candidates are generated by the
existing tokenizer's hash-chain matcher, then a bounded dynamic program
chooses between literals, REP candidates, and explicit matches.

The objective is a cheap structural cost proxy, not the final Huffman bit
cost. This keeps the experiment deterministic and independent of the entropy
coding implementation.
"""
from __future__ import annotations

from .lz import LIT, MATCH, REP, MIN_MATCH, DEFAULT_MAX_MATCH, DEFAULT_WINDOW


def _match_length(data, a, b, limit):
    n = len(data)
    limit = min(limit, n - a, n - b)
    l = 0
    while l < limit and data[a + l] == data[b + l]:
        l += 1
    return l


def _candidates(data, i, window, max_match, max_chain, reps):
    """Return deterministic (length, distance, rep_index) candidates."""
    n = len(data)
    limit = min(max_match, n - i)
    out = []

    # REP candidates are cheap and must be considered explicitly.
    for ri, d in enumerate(reps):
        if d <= 0 or d > i or d > window:
            continue
        l = _match_length(data, i - d, i, limit)
        if l >= MIN_MATCH:
            out.append((l, d, ri))

    if i + MIN_MATCH > n:
        return out

    key = data[i:i + MIN_MATCH]
    start = max(0, i - window)
    # Build a local backwards scan. The bounded parser is an experiment, so
    # keeping this isolated avoids changing the production match finder.
    tried = 0
    p = i - MIN_MATCH
    while p >= start and tried < max_chain:
        if data[p:p + MIN_MATCH] == key:
            d = i - p
            l = _match_length(data, p, i, limit)
            if l >= MIN_MATCH:
                out.append((l, d, -1))
        p -= 1
        tried += 1

    # Keep only useful lengths. Every candidate beyond the first occurrence
    # of a given length/distance is redundant for the DP state.
    seen = set()
    unique = []
    for item in sorted(out, key=lambda x: (-x[0], x[1], x[2])):
        if item not in seen:
            seen.add(item)
            unique.append(item)
    return unique


def _token_cost(length, distance, rep_index):
    """Cheap monotonic approximation of DE2 token cost in bits."""
    if rep_index >= 0:
        # REP has no explicit distance payload.
        return 3 + max(1, length.bit_length())
    return 8 + max(1, length.bit_length()) + max(1, distance.bit_length())


def tokenize_bounded(data, lookahead=64, window_size=DEFAULT_WINDOW,
                     max_chain=32, max_match=DEFAULT_MAX_MATCH):
    """Choose a bounded minimum-cost token path.

    The DP is restricted to ``lookahead`` bytes from the current position.
    State includes the two most recent distances because REP legality depends
    on them. The implementation is intentionally conservative and suitable
    for benchmark experiments, not yet for production use.
    """
    if not isinstance(data, bytes):
        data = bytes(data)
    if lookahead < 1:
        raise ValueError("lookahead must be >= 1")
    n = len(data)
    if n == 0:
        return []

    # Recursive memoized search over a bounded horizon. For each decision we
    # only evaluate candidates starting at the current position. The horizon
    # is deliberately small to keep the experiment tractable in Python.
    from functools import lru_cache

    def solve(start, reps0, reps1):
        end = min(n, start + lookahead)

        @lru_cache(maxsize=None)
        def dp(i, r0, r1):
            if i >= end:
                return 0, ()
            best_cost = 8 + dp(i + 1, r0, r1)[0]
            best = ((LIT, data[i]),) + dp(i + 1, r0, r1)[1]

            reps = tuple(x for x in (r0, r1) if x)
            for length, dist, ri in _candidates(
                    data, i, window_size, max_match, max_chain, reps):
                stop = min(length, end - i)
                for l in range(MIN_MATCH, stop + 1):
                    ni = i + l
                    if ri >= 0:
                        nr0, nr1 = (r1, r0) if ri == 1 else (r0, r1)
                        # REP0 keeps ordering; REP1 swaps it.
                        if ri == 1:
                            nr0, nr1 = r1, r0
                        cost = _token_cost(l, dist, ri) + dp(ni, nr0, nr1)[0]
                        if cost < best_cost:
                            best_cost = cost
                            best = ((REP, l, ri),) + dp(ni, nr0, nr1)[1]
                    else:
                        nr0, nr1 = (dist, r0)
                        cost = _token_cost(l, dist, -1) + dp(ni, nr0, nr1)[0]
                        if cost < best_cost:
                            best_cost = cost
                            best = ((MATCH, l, dist),) + dp(ni, nr0, nr1)[1]
            return best_cost, best

        return dp(start, reps0, reps1)[1]

    # Re-run bounded searches over successive blocks. This deliberately avoids
    # changing the production parser while making the experimental behavior
    # measurable. A block boundary may reduce global optimality.
    tokens = []
    i = 0
    reps = []
    while i < n:
        block = solve(i, reps[0] if reps else 0, reps[1] if len(reps) > 1 else 0)
        if not block:
            tokens.append((LIT, data[i]))
            i += 1
            continue
        # ``solve`` may only see the bounded horizon; emit the first token and
        # advance one decision at a time so the next horizon can reconsider it.
        tok = block[0]
        tokens.append(tok)
        if tok[0] == LIT:
            i += 1
        elif tok[0] == MATCH:
            dist = tok[2]
            if dist in reps:
                reps.remove(dist)
            reps.insert(0, dist)
            reps[:] = reps[:2]
            i += tok[1]
        else:
            if tok[2] == 1 and len(reps) >= 2:
                reps[0], reps[1] = reps[1], reps[0]
            i += tok[1]
    return tokens


__all__ = ["tokenize_bounded"]
